services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: cd packages/api/ && yarn install && yarn build
    startCommand: rsync -a packages/api/public/ /data/public/ && cd packages/api/ && yarn start
    healthCheckPath: /_health
    # disk:
    #   name: strapi-data
    #   mountPath: /data
    #   sizeGB: 1
    # envVars:
    #   - key: NODE_VERSION
    #     value: 14.17.0
    #   - key: NODE_ENV
    #     value: production
    #   - key: DATABASE_FILENAME
    #     value: /data/strapi.db
    #   - key: JWT_SECRET
    #     generateValue: true
    #   - key: ADMIN_JWT_SECRET
    #     generateValue: true
        
    envVars:
      - key: NODE_VERSION
        value: 14.17.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true

databases:
  - name: strapi
    plan: starter